// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/product.proto

package product

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Product struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Desc                 string   `protobuf:"bytes,3,opt,name=desc" json:"desc,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Product) Reset()         { *m = Product{} }
func (m *Product) String() string { return proto.CompactTextString(m) }
func (*Product) ProtoMessage()    {}
func (*Product) Descriptor() ([]byte, []int) {
	return fileDescriptor_product_460b9ec380a92816, []int{0}
}
func (m *Product) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Product.Unmarshal(m, b)
}
func (m *Product) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Product.Marshal(b, m, deterministic)
}
func (dst *Product) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Product.Merge(dst, src)
}
func (m *Product) XXX_Size() int {
	return xxx_messageInfo_Product.Size(m)
}
func (m *Product) XXX_DiscardUnknown() {
	xxx_messageInfo_Product.DiscardUnknown(m)
}

var xxx_messageInfo_Product proto.InternalMessageInfo

func (m *Product) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Product) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Product) GetDesc() string {
	if m != nil {
		return m.Desc
	}
	return ""
}

type AddProductResp struct {
	Success              bool     `protobuf:"varint,1,opt,name=success" json:"success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddProductResp) Reset()         { *m = AddProductResp{} }
func (m *AddProductResp) String() string { return proto.CompactTextString(m) }
func (*AddProductResp) ProtoMessage()    {}
func (*AddProductResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_product_460b9ec380a92816, []int{1}
}
func (m *AddProductResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddProductResp.Unmarshal(m, b)
}
func (m *AddProductResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddProductResp.Marshal(b, m, deterministic)
}
func (dst *AddProductResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddProductResp.Merge(dst, src)
}
func (m *AddProductResp) XXX_Size() int {
	return xxx_messageInfo_AddProductResp.Size(m)
}
func (m *AddProductResp) XXX_DiscardUnknown() {
	xxx_messageInfo_AddProductResp.DiscardUnknown(m)
}

var xxx_messageInfo_AddProductResp proto.InternalMessageInfo

func (m *AddProductResp) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

type AddProductReq struct {
	Data                 *Product `protobuf:"bytes,1,opt,name=Data" json:"Data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddProductReq) Reset()         { *m = AddProductReq{} }
func (m *AddProductReq) String() string { return proto.CompactTextString(m) }
func (*AddProductReq) ProtoMessage()    {}
func (*AddProductReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_product_460b9ec380a92816, []int{2}
}
func (m *AddProductReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddProductReq.Unmarshal(m, b)
}
func (m *AddProductReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddProductReq.Marshal(b, m, deterministic)
}
func (dst *AddProductReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddProductReq.Merge(dst, src)
}
func (m *AddProductReq) XXX_Size() int {
	return xxx_messageInfo_AddProductReq.Size(m)
}
func (m *AddProductReq) XXX_DiscardUnknown() {
	xxx_messageInfo_AddProductReq.DiscardUnknown(m)
}

var xxx_messageInfo_AddProductReq proto.InternalMessageInfo

func (m *AddProductReq) GetData() *Product {
	if m != nil {
		return m.Data
	}
	return nil
}

type GetProductReq struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetProductReq) Reset()         { *m = GetProductReq{} }
func (m *GetProductReq) String() string { return proto.CompactTextString(m) }
func (*GetProductReq) ProtoMessage()    {}
func (*GetProductReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_product_460b9ec380a92816, []int{3}
}
func (m *GetProductReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetProductReq.Unmarshal(m, b)
}
func (m *GetProductReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetProductReq.Marshal(b, m, deterministic)
}
func (dst *GetProductReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetProductReq.Merge(dst, src)
}
func (m *GetProductReq) XXX_Size() int {
	return xxx_messageInfo_GetProductReq.Size(m)
}
func (m *GetProductReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetProductReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetProductReq proto.InternalMessageInfo

func (m *GetProductReq) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type GetProductResp struct {
	Data                 *Product `protobuf:"bytes,1,opt,name=Data" json:"Data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetProductResp) Reset()         { *m = GetProductResp{} }
func (m *GetProductResp) String() string { return proto.CompactTextString(m) }
func (*GetProductResp) ProtoMessage()    {}
func (*GetProductResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_product_460b9ec380a92816, []int{4}
}
func (m *GetProductResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetProductResp.Unmarshal(m, b)
}
func (m *GetProductResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetProductResp.Marshal(b, m, deterministic)
}
func (dst *GetProductResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetProductResp.Merge(dst, src)
}
func (m *GetProductResp) XXX_Size() int {
	return xxx_messageInfo_GetProductResp.Size(m)
}
func (m *GetProductResp) XXX_DiscardUnknown() {
	xxx_messageInfo_GetProductResp.DiscardUnknown(m)
}

var xxx_messageInfo_GetProductResp proto.InternalMessageInfo

func (m *GetProductResp) GetData() *Product {
	if m != nil {
		return m.Data
	}
	return nil
}

func init() {
	proto.RegisterType((*Product)(nil), "product.Product")
	proto.RegisterType((*AddProductResp)(nil), "product.AddProductResp")
	proto.RegisterType((*AddProductReq)(nil), "product.AddProductReq")
	proto.RegisterType((*GetProductReq)(nil), "product.GetProductReq")
	proto.RegisterType((*GetProductResp)(nil), "product.GetProductResp")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for ProductDetail service

type ProductDetailClient interface {
	AddProduct(ctx context.Context, in *AddProductReq, opts ...grpc.CallOption) (*AddProductResp, error)
	GetProduct(ctx context.Context, in *GetProductReq, opts ...grpc.CallOption) (*GetProductResp, error)
}

type productDetailClient struct {
	cc *grpc.ClientConn
}

func NewProductDetailClient(cc *grpc.ClientConn) ProductDetailClient {
	return &productDetailClient{cc}
}

func (c *productDetailClient) AddProduct(ctx context.Context, in *AddProductReq, opts ...grpc.CallOption) (*AddProductResp, error) {
	out := new(AddProductResp)
	err := grpc.Invoke(ctx, "/product.ProductDetail/AddProduct", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productDetailClient) GetProduct(ctx context.Context, in *GetProductReq, opts ...grpc.CallOption) (*GetProductResp, error) {
	out := new(GetProductResp)
	err := grpc.Invoke(ctx, "/product.ProductDetail/GetProduct", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for ProductDetail service

type ProductDetailServer interface {
	AddProduct(context.Context, *AddProductReq) (*AddProductResp, error)
	GetProduct(context.Context, *GetProductReq) (*GetProductResp, error)
}

func RegisterProductDetailServer(s *grpc.Server, srv ProductDetailServer) {
	s.RegisterService(&_ProductDetail_serviceDesc, srv)
}

func _ProductDetail_AddProduct_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddProductReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductDetailServer).AddProduct(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/product.ProductDetail/AddProduct",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductDetailServer).AddProduct(ctx, req.(*AddProductReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductDetail_GetProduct_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProductReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductDetailServer).GetProduct(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/product.ProductDetail/GetProduct",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductDetailServer).GetProduct(ctx, req.(*GetProductReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _ProductDetail_serviceDesc = grpc.ServiceDesc{
	ServiceName: "product.ProductDetail",
	HandlerType: (*ProductDetailServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddProduct",
			Handler:    _ProductDetail_AddProduct_Handler,
		},
		{
			MethodName: "GetProduct",
			Handler:    _ProductDetail_GetProduct_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/product.proto",
}

func init() { proto.RegisterFile("proto/product.proto", fileDescriptor_product_460b9ec380a92816) }

var fileDescriptor_product_460b9ec380a92816 = []byte{
	// 230 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x91, 0xc1, 0x4b, 0x87, 0x30,
	0x14, 0xc7, 0x7f, 0x53, 0xc9, 0x7a, 0xa1, 0xc4, 0x0b, 0x6a, 0x74, 0x49, 0x46, 0x07, 0xe9, 0x60,
	0x60, 0xd4, 0x35, 0x04, 0xa1, 0x6b, 0xec, 0x3f, 0x58, 0xdb, 0x0e, 0x42, 0xe5, 0x72, 0xf3, 0x0f,
	0xe9, 0x3f, 0x0e, 0xa7, 0xe6, 0x8c, 0x0e, 0xdd, 0xde, 0xfb, 0xfa, 0x7d, 0x1f, 0x3e, 0x32, 0x38,
	0x37, 0x43, 0xef, 0xfa, 0x3b, 0x33, 0xf4, 0x6a, 0x94, 0xae, 0xf2, 0x1b, 0xa6, 0xcb, 0xca, 0x1a,
	0x48, 0x5f, 0xe6, 0x11, 0x73, 0x88, 0x3a, 0x45, 0x49, 0x41, 0xca, 0x98, 0x47, 0x9d, 0x42, 0x84,
	0xe4, 0x43, 0xbc, 0x6b, 0x1a, 0x15, 0xa4, 0x3c, 0xe1, 0x7e, 0x9e, 0x32, 0xa5, 0xad, 0xa4, 0xf1,
	0x9c, 0x4d, 0x33, 0xbb, 0x85, 0xbc, 0x51, 0x6a, 0xa1, 0x70, 0x6d, 0x0d, 0x52, 0x48, 0xed, 0x28,
	0xa5, 0xb6, 0xd6, 0xe3, 0x8e, 0xf9, 0xba, 0xb2, 0x07, 0xc8, 0xc2, 0xee, 0x27, 0xde, 0x40, 0xd2,
	0x0a, 0x27, 0x7c, 0xef, 0xb4, 0x3e, 0xab, 0x56, 0xcd, 0xb5, 0xe2, 0xbf, 0xb2, 0x6b, 0xc8, 0x9e,
	0xb5, 0x0b, 0xce, 0x7e, 0xb9, 0xb2, 0x47, 0xc8, 0xc3, 0x82, 0x35, 0xff, 0x03, 0xd7, 0x5f, 0x04,
	0xb2, 0x25, 0x69, 0xb5, 0x13, 0xdd, 0x1b, 0x3e, 0x01, 0x6c, 0x86, 0x78, 0xf1, 0x73, 0xb7, 0xd3,
	0xbe, 0xba, 0xfc, 0x33, 0xb7, 0x86, 0x1d, 0x26, 0xc0, 0xa6, 0x12, 0x00, 0x76, 0x3f, 0x10, 0x00,
	0xf6, 0xde, 0xec, 0xf0, 0x7a, 0xe4, 0x9f, 0xe8, 0xfe, 0x3b, 0x00, 0x00, 0xff, 0xff, 0x06, 0x6c,
	0x8e, 0x56, 0xb9, 0x01, 0x00, 0x00,
}
